export const InputStyles = Object.freeze({
    Default: [
        'text-grey-600',
        'text-lg',
        'border',
        'focus:border-transparent',
        'border-grey-300',
        'rounded-lg',
        'ring',
        'ring-transparent',
        'focus:ring-2',
        'focus:outline-none',
        'focus:ring-primary-500',
        'block',
        'bg-white',
        'w-full',
        'p-2.5',
        'rounded-l-lg',
        'py-3',
        'px-4',
    ].join(' '),
    Hover: [
        'hover:border-primary-500',
        'hover:placeholder-primary-500',
        'hover:text-primary-500',
    ].join(' '),
    Pad: 'pl-12',
    Readonly: ['bg-gray-100', 'cursor-pointer'].join(' '),
})
